### PR TITLE
Enable Travis tests, make 'meld . ../LambdaHack' easier, update and tweak

### PR DESCRIPTION
**Pull request by Mikolaj**

### CODE REVIEW

**Comment by tuturto** [comment]
Great work, very much appreciated.

**Comment by Mikolaj** [comment]
You are welcome. ;)

**Comment by Mikolaj** [comment]
BTW, if you log in to Travis, e.g., with you github credentials, you can enable Travis for the repo and you'd get automatic builds at commits.

**Comment by tuturto** [comment]
I enabled those now and added a build badge. It might be, that the build doesn't work out (we'll see in a moment I suppose), since space privateers is currently using LambdaHack from the master branch (and not a released one).

**Comment by tuturto** [comment]
Actually, it works, since .travis.yml is configured to checkout LambdaHack from your repository. Mighty cool.

**Pull request merged**
